### ISSUE TITLE
The crash handler processes almost never stop

### ISSUE THREAD

**Issue by macqm** [google/omaha#143]
It looks like the crash handler processes listen to an even (named object, `kShutdownEvent`) and the `ShutdownHandler` terminates the crash handler once the event is signalled.

However, this event is never signalled, execpt for the Setup process in `Setup::SignalShutdownEvent()`.

That causes the CrashHandler go listen all the time, even if none of the omaha processes are running (e.g. `/c` or `/ua` modes). Once it runs it stays opened. E.g. in GoogleUpdate and Chrome I can see these two processes hanging around:
![image](https://user-images.githubusercontent.com/1261267/53378369-2ee1e580-391a-11e9-816a-089d6a543738.png)

Is this design intentional or is this a bug?

**Comment by sorinj** [comment]
It is intentional. These crash handlers watch other Omaha processes, and capture an out of process crash when it occurs. The crash handlers run even if the usage stats are off, since Omaha always captures the crash even if the crash is only uploaded when it is allowed to.

**Comment by sorinj** [comment]
It just happens to work that way, the design is intentional, but it is clearly suboptimal. It has to do with a lot of technical debt on how the crash handler in Chrome used to work. The crash handlers are going to be running when at least one of the apps managed by Omaha has opted in sending usage stats.

There was no way for a Breakpad client to start/stop a crash handler as needed, and there was a time when Omaha would run its /c mode continuously. We ended up with this odd situation where the crash handlers would run when they were not needed.

**Comment by peeped76** [comment]
เกิดการผิดพลาด
