### ISSUE TITLE
fatal error C1083: No such file or directory

### ISSUE THREAD

**Issue by Mohan-V-P** [google/omaha#216]
I was building the omaha. i got an error like this.
**C:\omaha\omaha/common/exception_handler.h(29): fatal error C1083: Cannot open include file: 'third_party/breakpad/src/client/windows/crash_generation/client_info.h': No such file or directory**.
I searched in omaha\third_party\     the breakpad directory is missing and even i searched in 
third_party\       the breakpad directory is missing. What should i do?

**Comment by sorinj** [comment]
Breakpad needs to be manually installed as a third-party dependency, since breakpad is not part of this checkout. Please follow the instructions [here](https://github.com/google/omaha/blob/master/doc/DeveloperSetupGuide.md), the section about third party dependencies. In the future we may include all the third-party dependencies in this repository but we don't have a way to roll them and keep them up to date, so people still need to do a bit of work.

**Comment by Mohan-V-P** [comment]
Thank you very much.
