### ISSUE TITLE
omaha/hammer.bat should not overwrite already-defined variables

### ISSUE THREAD

**Issue by sparist** [google/omaha#317]
If omaha/hammer.bat did not overwrite already-defined variables, and only applied the default when the variable was not defined, then it would be possible to use hammer.bat with different paths (via environment variables) without having to change the file itself.

**Comment by sparist** [comment]
Closed by https://github.com/google/omaha/pull/316

**Comment by David123-gif** [comment]
David Covington has sent you an email via Gmail confidential mode:

[image: Gmail logo]Re: [google/omaha] omaha/hammer.bat should not overwrite already-defined variables (#317) <https://confidential-mail.google.com/msg/ACnmsxFaKWNMHGGtA6M6xkQW8JxtYMpE2FNiJIIpXtcIXGXNWoaG3ZH25toUN6F7DeMPKBXk8s1AM6Ax0OpnnXsPvyJqoR8agRW5bvkoENGecR-1voL3viD4O5FnFgT8BmRvvua8MIYcrhqOSj8jXJ8N5AIjxodY5h4gnALxpeRGOv60805J_U_hhJFq7yn3E--M57W8O_E8wLG_ByM=>

This message was sent on Dec 9, 2021 at 12:35:28 PM PST
You can open it by clicking the link below. This link will only work for ***@***.***

View the email <https://confidential-mail.google.com/msg/ACnmsxFaKWNMHGGtA6M6xkQW8JxtYMpE2FNiJIIpXtcIXGXNWoaG3ZH25toUN6F7DeMPKBXk8s1AM6Ax0OpnnXsPvyJqoR8agRW5bvkoENGecR-1voL3viD4O5FnFgT8BmRvvua8MIYcrhqOSj8jXJ8N5AIjxodY5h4gnALxpeRGOv60805J_U_hhJFq7yn3E--M57W8O_E8wLG_ByM=>

Gmail confidential mode gives you more control over the messages you send. The sender may have chosen to set an expiration time, disable printing or forwarding, or track access to this message. Learn more <https://support.google.com/mail/answer/7674059>
Gmail: Email by Google
Use is subject to the Google Privacy Policy <https://myaccount.google.com/privacypolicy?hl=en>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
You have received this message because someone sent you an email via Gmail confidential mode.
[image: Google logo]
