### ISSUE TITLE
Build dependency issue exposed during multi-core build

### ISSUE THREAD

**Issue by turquoiseowl** [google/omaha#403]
After doing a replace-all and rename-all for the token ```goop``` -> ```topo``` across all files and folders in the project, I get build failures with the error:

```LINK : fatal error LNK1104: cannot open file 'c:\omaha\scons-out\opt-win\lib\topodate_lib_64.lib'```

while linking ```GoogleUpdateComRegisterShell64_unsigned.exe``` - BUT only if i enable 3 cores or more for the build (-j3) !

Without doing the replace/rename thing, there is no build error; same if I do do the rename/replace thing but only use 1 or 2 build cores.

After some investigation, it seems there is a missing dependency of ```GoogleUpdateComRegisterShell64_unsigned.exe``` on  ```topodate_lib_64.lib``` which doesn't break the build if the lib is called ```goopdate_lib_64.lib``` because it is sequenced to be built earlier on (due to alphanumeric ordering) so happens to be built in time even when build is mega parallel.

I'm not too familiar with SCONS so am hoping someone who is would be able to look into it please, to see if there is a missing dependency of ```GoogleUpdateComRegisterShell64_unsigned.exe``` on  ```goopdate_lib_64.lib```?

Many thanks.

**Comment by sorinj** [comment]
Thank you for raising the issue, my intention is to look into this soon.

**Comment by turquoiseowl** [comment]
I'm working around this by looping the hammer invocation a few times (with -j7), so okay by me to mark this issue as a TODO and close for now. Thanks.

**Comment by sorinj** [comment]
It is possible that the concurrent build in this version old version of scons we are using is broken in some mysterious way.

I see no obvious problem with the dependencies. Running the following command shows that the target depends on 
`hammer -Q --tree=prune scons-out\dbg-win\staging\GoogleUpdateComRegisterShell64.exe`

```
+-scons-out\dbg-win\staging\GoogleUpdateComRegisterShell64.exe
  +-scons-out\dbg-win\obj\goopdate\GoogleUpdateComRegisterShell64.exe
    +-scons-out\dbg-win\obj\goopdate\GoogleUpdateComRegisterShell64_unsigned.exe
...
    | +-scons-out\dbg-win\obj\goopdate\com_register_shell.obj64
    | +-[scons-out\dbg-win\lib\logging_64.lib]
    | +-scons-out\dbg-win\lib\goopdate_lib_64.lib
```

I tested locally that touching `goopdate_lib_64.lib` results in rebuilding of  `GoogleUpdateComRegisterShell64.exe`. I ran builds with different `-j` values. No issue.

I suggest running the command above and inspecting the dependency tree in your case. The build flavor is selected using `--mode=opt-win` if you want to test opt instead of dbg.
