### ISSUE TITLE
shagayeg.k0815@gmail.com

### ISSUE THREAD

**Issue by Shagayegkarimy** [google/omaha#653]
Hello, I suffered a spinal cord injury due to a car overturning, and I am unable to complete the forms and method of reimbursement. I am asking for help.

**Comment by Shagayegkarimy** [comment]
shagayeg.k0815@gmail.com

**Comment by WilliamAaron** [comment]
?  Yes I have suffered a spinal cord injury I broke my neck 3 vertebra so bad that all 3 were removed and bone from my pelvic was harvested and grafted in with some titanium, and I’m told some kind of silicone, my spinal cord sits in. Somehow I came away with minimal damage I would say, although I’ve been unable to do some things since age 26 when it happened. it was a very very unfortunate vehicle accident that I was the complete victim of sad. It was a rich person that did it and well. The hospital sent me home with a broken neck still somehow I came out of it, and I even died for about seven or eight minutes in the vehicle to hell of a deal but I make the most of it and what are you talking about? I get people all the time from over there saying something I have no idea what they want. Do you need to talk about the spinal cord injury stuff actually I’d like to speak with somebody else that had one because people just don’t understand. Luckily, I only had partial paralysis on my left side which I’ve overcome most of , but there is a little bit doesn’t work on me so you deal with it so far I have over come but I am on antidepressants and coming out hopefully of a depression that I’ve been in for about two years. I’m starting to feel better not only Covid, but I had to have double hip surgery. It took me two years, for I could fix my vehicle just getting old. What is it y’all keep contacting me about I don’t trust anybody not anymore not after I can’t tell you how many times I’ve had hackers attack me and well I don’t trust anyone anymore. I don’t know about the only one I do know that I trust it’s in the IT business is my uncle who teaches cyber security he’s about the only one he used to be good at this crap not anymore, so if y’all. are legit from GitHub because seen too many fake sites fake addresses everything else it’s bull crap I won’t even touch my email because half the time I do it’s a trap just waiting to activate. I don’t even dare go near my old yahoo accounts, which I’d love to have the pictures from and other information but every time I try to go there it’s a guaranteed attack or something I have to do on a computer or something somebody’s gonna have to walk me through it understood stuff until windows XP or so I was OK with seven it went to eight or I should say ever since seven eight nine! it’s supposed to be a joke when does 10 just confused me when does is just yeah android about the same and I don’t even want to go there on this iPhone. I’ve been trying to learn it for years about the time I think I got it figured out everything changes with an update when it comes to code, you should’ve had a time X or TI 9948 or a trash 80 or I should say TR 80 Tandy  corporation because back then I could do stuff on the computers like coding but not poor and yes, my first computer was time x  with an outstanding one K2K if you put in the expansion module I actually had two different models. I think that’s all they built before they went to pure calculators then it was Texas instruments TI 99 4a Test and just up from there besides being a ham radio operator for three licenses, all because things have happened to me over the years and just didn’t get around toRecertified my license each time because I was busy with other things in life my current ham is active soda, said uncle that does cyber security it’s a dying art back when I did it, you really had to know electronics which I did teach myself at age 14, then took a high school course and it was college level but yeah, that was all before the wreck and hit my head and now have well disassociated schizophrenia from it if I don’t stay on my medicine wish I could still do that. One of my friends is kind of like that. He taught himself python. I’ve been trying to do that for years just mind-boggling I guess I should’ve grown up with the concept of a program to write the program not yeah my first email address you had to write the program to send the email to the bulletin board server , or you could do it with the ham over packet that was back in the day no if you aren’t real people, I suggest leave me alone said cyber security uncle plus another uncle who works in well human services will have a field day with y’all, Sister is a lawyer from  Baylor law school top of her class very top yes dislike my big sister with two PhD‘s top of her class ones for a Pharmacy UT Austin. She actually is a professor here in Tyler also yeah I’ve got a lot to say I don’t get over get tired of talking , I love life too much. What do y’all want? Do you want to get a hold of me? I’ll give you a damn phone number. Tell me what you want. The funny thing is I’m watching a show right now on the dude who wrote most of the stuff well in windows, along with the dude who wrote some of the stuff in windows doing the podcast , anyway, how can I help you? I should say if y’all are the real people cause like I said I don’t trust anybody anymore trying to contact me this is all gonna get screenshot it and send my uncle if anything weird happens. Sent from my iPhoneOn Dec 2, 2023, at 1:20 AM, Shagayegkarimy ***@***.***> wrote:﻿
***@***.***
